---

- name: Enable routing in kernel
  sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    sysctl_set: yes
    state: present
    reload: yes

- name: Copy config template
  template:
    src: bird.conf.j2
    dest: /etc/bird.conf
    owner: root
    group: bird
    mode: '0440'
  notify: restart bird

- name: Start/enable bird
  systemd:
    name: bird.service
    state: started
    enabled: yes

...
