---

- name: Create client key directory
  file:
    path: /etc/openvpn/client-configs/keys
    state: directory
    mode: "0700"

- name: Create client cert requests
  command: ./easyrsa gen-req {{ item }} nopass
  args:
    chdir: "/root/{{ easyrsa.version }}"
    creates: "/root/{{ easyrsa.version }}/pki/private/{{ item }}.key"
  environment:
    EASYRSA_BATCH: 1
  with_items: "{{ openvpn.connection }}"

- name: Sign client cert requests
  command: ./easyrsa sign-req client {{ item }}
  args:
    chdir: "/root/{{ easyrsa.version }}"
    creates: "/root/{{ easyrsa.version }}/pki/issued/{{ item }}.crt"
  environment:
    EASYRSA_BATCH: 1
  with_items: "{{ openvpn.connection }}"
