---

- name: Create client key directory
  file:
    path: /etc/openvpn/client-configs/keys
    state: directory
    mode: "0700"

- name: Create client cert requests
  command: ./easyrsa gen-req {{ item }} nopass
  args:
    chdir: "/root/{{ easyrsa.version }}"
    creates: "/root/{{ easyrsa.version }}/pki/private/{{ item }}.key"
  environment:
    EASYRSA_BATCH: 1
  with_items: "{{ openvpn.connection }}"

- name: Sign client cert requests
  command: ./easyrsa sign-req client {{ item }}
  args:
    chdir: "/root/{{ easyrsa.version }}"
    creates: "/root/{{ easyrsa.version }}/pki/issued/{{ item }}.crt"
  environment:
    EASYRSA_BATCH: 1
  with_items: "{{ openvpn.connection }}"

- name: Copy ta.key and ca.crt files to /etc/openvpn/client-configs/keys
  copy:
    src: "{{ item }}"
    dest: /etc/openvpn/client-configs/keys
    remote_src: yes
  with_items:
    - "/root/{{ easyrsa.version }}/ta.key"
    - "/etc/openvpn/ca.crt"

- name: Copy .crt files to /etc/openvpn/client-configs/keys
  copy:
    src: "/root/{{ easyrsa.version }}/pki/issued/{{ item }}.crt"
    dest: /etc/openvpn/client-configs/keys
    remote_src: yes
  with_items: "{{ openvpn.connection }}"


- name: Copy .key files to /etc/openvpn/client-configs/keys
  copy:
    src: "/root/{{ easyrsa.version }}/pki/private/{{ item }}.key"
    dest: /etc/openvpn/client-configs/keys
    remote_src: yes
  with_items: "{{ openvpn.connection }}"

...
