---

- name: Install EPEL
  yum:
    name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm"
    state: installed

- name: Install OpenVPN
  yum:
    name: openvpn
    state: present

- name: Download EasyRSA
  get_url: 
    url: "https://github.com/OpenVPN/easy-rsa/releases/download/v3.0.7/{{ easyrsa.version }}.tgz"
    dest: "/root/{{ easyrsa.version }}.tgz"

- name: Create EasyRSA directory
  file:
    path: "/root/{{ easyrsa.version }}"
    state: directory

- name: Extract EasyRSA
  unarchive: 
    src: "/root/{{ easyrsa.version }}.tgz"
    dest: /root
    remote_src: yes

- name: Copy EasyRSA required variables
  template:
    src: easyrsa.j2
    dest: "/root/{{ easyrsa.version }}/vars"

...
